<?=$this->doctype(); ?>

<html lang="en">
	<head>
		<meta charset="utf-8">
		<?=$this->headTitle( $this->translate( 'Seductive Craft' ) )->setSeparator( ' - ' )->setAutoEscape( false ) ?>

		<?=$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

		<!-- Le styles -->
		<?=$this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
		                ->prependStylesheet($this->basePath() . '/style.css');
?>
		<!-- Scripts -->
		<?=$this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
		                              ->prependFile($this->basePath() . '/js/jquery-1.7.2.min.js') ?>

	</head>

	<body>
		<div id="header">
			<div id="top">
				<div class="container_12">
					<div class="grid_9">
						<div id="second_nav">
							<ul class="sf-menu">
								<li class="first"><a href="/">Home</a></li>
								<li><a href="/forum/">Forum</a></li>
								<!--li><a href="#">Dropdowns</a>
									<ul>
										<li class="first"><a href="#">Dropdown One</a></li>
										<li><a href="#">Dropdown Two</a></li>
										<li class="last"><a href="#">Dropdown Three</a></li>
									</ul>
								</li-->
							</ul>
						</div><!--second_nav-->
					</div><!--grid_9-->
					<div class="clear"></div>
				</div><!--container_12-->
			</div><!--top-->
			<div id="bottom">
				<div class="container_12">
					<div class="grid_5">
						<div id="logo">
							<a id="first" href="/">Seductive</a>
							<a id="second" href="/">Craft</a>
						</div><!--logo-->
					</div><!--grid_5-->
					<div class="grid_7">
						<div id="header_advert">
							<img src="/images/banner.jpg" width="468" height="90" />
						</div><!--header_advert-->
					</div><!--grid_7-->
					<div class="clear"></div>
				</div><!--container_12-->
			</div><!--bottom-->
		</div><!--header-->

		<div id="the_body">
			<div class="container_12">
				<?=$this->content;?>
				<hr>
			</div>
		</div> <!-- /container -->
		<div id="footer">

		    <div class="container_12">
			
			<div class="grid_12">
			
			    <div id="footer_bg">
			    
				<div id="third_nav">
				
				    <ul>
					<li><span> // </span><a href="#">Elements</a></li>
					<li><span> // </span><a href="#">Archives</a></li>
					<li><span> // </span><a href="#">Full Width</a></li>
					<li><span> // </span><a href="#">Contact Form</a></li>
					<li><span> // </span><a href="#">Another 3.0 Menu</a></li>
				    </ul>
				    
				    <div id="back_to_top"><a href="#header"><span>Back to top </span><span class="arrow"></span></a></div>
				    
				</div><!--third_nav-->
				
				<div id="footer_bar"></div>
				
				<div class="column">
				
				    <div class="widget">
					
					<h6>About Duplex</h6>
					
					<p>The Duplex theme comes with support for WP3.0 menus and an extensive set of back-end options.</p>

					<p>The theme supports 10 widget locations and 8 custom-made widgets; 300x200 Ad Widget, 125x125 Ads Widget, 120x240 Ad Widget, Flickr Photos Widget, Latest Tweets Widget, Tabbed Content Widget, RSS Subscribers and Followers Widget and a Video Widget - Phew!</p>

					<p>Inbuilt related posts, contact form, author bios, archives template, threaded comments, shortcodes, image slider.... you get the idea ;)</p>
					
				    </div><!--widget-->
				
				</div><!--column-->
				
				<div class="column">
				
				    <div class="widget">
					
					<h6>Latest Posts</h6>
					
					<ul>
					    <li class="first"><a href="#">Skype 5.0 Beta for Mac Arrives… But Where's Facebook?</a></li>
					    <li><a href="#">Apple Fails to Fix iPhone Daylight Savings Time Alarm Bug</a></li>
					    <li><a href="#">71% of Internet Users Run Latest Version of Their Browsers</a></li>
					    <li><a href="#">Netgear Wants to Wirelessly Connect New Televisions</a></li>
					    <li><a href="#">With Homegrown Talent, a Rising Power on Long Island</a></li>
					    <li class="last"><a href="#">Displaying Shooting Touch, Knicks Return to Prime Time</a></li>
					</ul>
					
				    </div><!--widget-->
				
				</div><!--column-->
				
				<div class="column last">
				
				    <div class="widget">
					
					<h6>Flickr Photostream</h6>
					
					<div class="flickr">
					    
					    <div><a href="#"><img src="images/content/flickr.jpg" width="55" height="55" alt="flickr"></a></div>
					    <div><a href="#"><img src="images/content/flickr.jpg" width="55" height="55" alt="flickr"></a></div>
					    <div><a href="#"><img src="images/content/flickr.jpg" width="55" height="55" alt="flickr"></a></div>
					    <div class="last"><a href="#"><img src="images/content/flickr.jpg" width="55" height="55" alt="flickr"></a></div>
					    
					    <div><a href="#"><img src="images/content/flickr.jpg" width="55" height="55" alt="flickr"></a></div>
					    <div><a href="#"><img src="images/content/flickr.jpg" width="55" height="55" alt="flickr"></a></div>
					    <div><a href="#"><img src="images/content/flickr.jpg" width="55" height="55" alt="flickr"></a></div>
					    <div class="last"><a href="#"><img src="images/content/flickr.jpg" width="55" height="55" alt="flickr"></a></div>
					    
					    <div><a href="#"><img src="images/content/flickr.jpg" width="55" height="55" alt="flickr"></a></div>
					    <div><a href="#"><img src="images/content/flickr.jpg" width="55" height="55" alt="flickr"></a></div>
					    <div><a href="#"><img src="images/content/flickr.jpg" width="55" height="55" alt="flickr"></a></div>
					    <div class="last"><a href="#"><img src="images/content/flickr.jpg" width="55" height="55" alt="flickr"></a></div>
					    
					    <span class="clear"></span>
					    
					</div><!--flickr-->
					
				    </div><!--widget-->
				    
				    <div class="clear"></div>
				
				</div><!--column-->
				
				<div class="clear"></div>
				
			    </div><!--foote_bg-->
			    
			    <div id="footer_bottom">
			    
				<p class="left">Copyright 2010 <a href="index.html">Duplex</a>. All Rights Reserved.</p>
				   <p class="right"><a href="http://www.premiumpixels.com/duplex-html">Duplex template</a> by <a href="http://www.premiumpixels.com">Orman</a></p>
				
				<div class="clear"></div>
			    
			    </div><!--bottom-->
			    
			</div><!--grid_12-->
			
			<div class="clear"></div>
			    
		     </div><!--container_12-->
 
	</div>
	 <div class="clear"></div>
	<?=$this->inlineScript() ?>
	</body>
</html>
