<?=
$this->doctype ()
; ?>

<html lang="en">
<head>
	<meta charset="utf-8">
	<?=$this->headTitle ( $this->translate ( 'Seductive Craft' ) )->setSeparator ( ' - ' )->setAutoEscape ( false ) ?>

	<?=$this->headMeta ()->appendName ( 'viewport', 'width=device-width, initial-scale=1.0' ) ?>

	<!-- Le styles -->
	<?=$this->headLink (
	array (
	      'rel'   => 'shortcut icon',
	      'type'  => 'image/vnd.microsoft.icon',
	      'href'  => $this->basePath () . '/images/favicon.ico'
	)
)
	->prependStylesheet ( $this->basePath () . '/style.css' );
	?>
	<!-- Scripts -->
	<?=$this->headScript ()->prependFile ( $this->basePath () . '/js/html5.js', 'text/javascript', array ( 'conditional' => 'lt IE 9', ) )
	->prependFile ( $this->basePath () . '/js/jquery-1.7.2.min.js' ) ?>

</head>

<body>
<div id="header">
	<div id="top">
		<div class="container_12">
			<div class="grid_9">
				<div id="second_nav">
					<ul class="sf-menu">
						<li class="first"><a href="/">Home</a></li>
						<li><a href="/forum/">Forum</a></li>
						<!--li><a href="#">Dropdowns</a>
								  <ul>
									  <li class="first"><a href="#">Dropdown One</a></li>
									  <li><a href="#">Dropdown Two</a></li>
									  <li class="last"><a href="#">Dropdown Three</a></li>
								  </ul>
							  </li-->
					</ul>
				</div>
				<!--second_nav-->
			</div>
			<!--grid_9-->
			<div class="grid_3">
				<div id="right_nav">
					<ul class="sf-menu">
						<li>
							<a href="#" class='popup-trigger'>Login</a>
							<div class="popup">
								<form action="/forum/ucp.php?mode=login" method="post">
									<h3><a href="/forum/ucp.php?mode=login">Login</a>&nbsp; &bull; &nbsp; <a href="./forum/ucp.php?mode=register">Register</a></h3>
									<fieldset>
										<label for="username">Username:</label>&nbsp;
										<input type="text" name="username" id="username" size="10" title="Username" />
										<label for="password">Password:</label>&nbsp;
										<input type="password" name="password" id="password" size="10" title="Password" />
										<input type="submit" name="login" value="Login" />
									</fieldset>
								</form>
							</div>
						</li>
					</ul>
				</div>
			</div>
			<div class="clear"></div>
		</div>
		<!--container_12-->
	</div>
	<!--top-->
	<div id="bottom">
		<div class="container_12">
			<div class="grid_5">
				<div id="logo">
					<a id="first" href="/">Seductive</a>
					<a id="second" href="/">Games</a>
				</div>
				<!--logo-->
			</div>
			<!--grid_5-->
			<div class="grid_7">
				<div id="header_advert">
					<h3>A Gaming Community</h3>
				</div>
				<!--header_advert-->
			</div>
			<!--grid_7-->
			<div class="clear"></div>
		</div>
		<!--container_12-->
	</div>
	<!--bottom-->
</div>
<!--header-->

<div id="the_body">
	<div class="container_12">
		<?=$this->content;?>
		<hr>
	</div>
</div>
<!-- /container -->
<div id="footer">

	<div class="container_12">

		<div class="grid_12">

			<div id="footer_bg">

				<div id="third_nav">

					<ul>
						<li><span> // </span><a href="/">Home</a></li>
					</ul>
					<div id="back_to_top"><a href="#header"><span>Back to top </span><span class="arrow"></span></a>
					</div>

				</div>
				<!--third_nav-->

				<div id="footer_bar"></div>

				<div class="column">

					<div class="widget">

						<h6>Links</h6>
						<div>
							<ul>
								<li><a href="/">Home</a></li>
								<li><a href="/forum/">Forum</a></li>
								<li><a href="/apply/">Membership</a></li>
								<li><a href="/donate/">Donate</a></li>
							</ul>
						</div>
					</div>
					<!--widget-->

				</div>
				<!--column-->

				<div class="column">

					<div class="widget">

						<h6>Latest Posts</h6>

						<!--ul>
							<li class="first"><a href="#">Skype 5.0 Beta for Mac Arrives… But Where's
								Facebook?</a></li>
							<li><a href="#">Apple Fails to Fix iPhone Daylight Savings Time Alarm Bug</a></li>
							<li><a href="#">71% of Internet Users Run Latest Version of Their Browsers</a></li>
							<li><a href="#">Netgear Wants to Wirelessly Connect New Televisions</a></li>
							<li><a href="#">With Homegrown Talent, a Rising Power on Long Island</a></li>
							<li class="last"><a href="#">Displaying Shooting Touch, Knicks Return to Prime
								Time</a></li>
						</ul-->
						Disabled for now

					</div>
					<!--widget-->

				</div>
				<!--column-->

				<div class="column last">

					<div class="widget">

						<h6>Flickr Photostream</h6>

						<div class="flickr">

							<!--div>
								<a href="#"><img src="images/content/flickr.jpg" width="55" height="55" alt="flickr"></a>
							</div>
							<div>
								<a href="#"><img src="images/content/flickr.jpg" width="55" height="55" alt="flickr"></a>
							</div>
							<div>
								<a href="#"><img src="images/content/flickr.jpg" width="55" height="55" alt="flickr"></a>
							</div>
							<div class="last">
								<a href="#"><img src="images/content/flickr.jpg" width="55" height="55" alt="flickr"></a>
							</div>

							<div>
								<a href="#"><img src="images/content/flickr.jpg" width="55" height="55" alt="flickr"></a>
							</div>
							<div>
								<a href="#"><img src="images/content/flickr.jpg" width="55" height="55" alt="flickr"></a>
							</div>
							<div>
								<a href="#"><img src="images/content/flickr.jpg" width="55" height="55" alt="flickr"></a>
							</div>
							<div class="last">
								<a href="#"><img src="images/content/flickr.jpg" width="55" height="55" alt="flickr"></a>
							</div>

							<div>
								<a href="#"><img src="images/content/flickr.jpg" width="55" height="55" alt="flickr"></a>
							</div>
							<div>
								<a href="#"><img src="images/content/flickr.jpg" width="55" height="55" alt="flickr"></a>
							</div>
							<div>
								<a href="#"><img src="images/content/flickr.jpg" width="55" height="55" alt="flickr"></a>
							</div>
							<div class="last">
								<a href="#"><img src="images/content/flickr.jpg" width="55" height="55" alt="flickr"></a>
							</div-->
							Disabled for now
							<span class="clear"></span>
						</div>
						<!--flickr-->
					</div>
					<!--widget-->
					<div class="clear"></div>
				</div>
				<!--column-->
				<div class="clear"></div>
			</div>
			<!--foote_bg-->
			<div id="footer_bottom">
				<p class="left">&copy; 2012 <a href="/">Seductive Turtle</a>. All Rights Reserved.</p>
				<div class="clear"></div>
			</div>
			<!--bottom-->
		</div>
		<!--grid_12-->
		<div class="clear"></div>
	</div>
	<!--container_12-->
</div>
<div class="clear"></div>
<script type="text/javascript" src="/js/jquery.easing.1.3.js"></script>
<script type="text/javascript" src="/js/superfish.js"></script>
<script type="text/javascript" src="/js/jquery.cycle.all.min.js"></script>
<script type="text/javascript" src="/js/jquery-ui-1.8.5.custom.min.js"></script>
<script type="text/javascript" src="/js/custom.js"></script>
</body>
</html>
