<div id="full_bg" class="grid_12">
	<div class="grid_12 alpha omega">
		<div id="nav">
			<ul class="sf-menu">
				<li class="first"><a href="#">Home</a></li>
				<li class="second"><a href="/forum/" target="_blank">Forum</a></li>
			</ul>
			<div class="clear"></div>
		</div>
		<!--nav-->
	</div>
	<!--grid_12-->
	<div class="grid_12 alpha omega">
		<div id="slider">
			<div class="item">
				<div class="image"><!--a href="#"><img src="images/content/slider_pic.jpg" alt="slider image"></a--></div>
				<div class="details">
					<div class="cats">
						<span>&nbsp;//&nbsp;</span> Aaron Scherer
						<span>&nbsp;//&nbsp;</span> August 27, 2012
					</div>
					<!--cats-->
					<h2><a href="#">New Site!</a></h2>

					<div class="excerpt">
						<p>Hey Guys! Working on the new site, so bear with me while i finish it!</p>
					</div>
					<!--excerpt-->
				</div>
				<!--details-->
				<div class="clear"></div>
			</div>
			<!--item-->
		</div>
		<!--slider-->
		<div id="slider_nav">
			<ul></ul>
		</div>
		<!--nav-->
	</div>
	<!--grid_12-->
	<div class="grid_12 alpha omega">
		<div class="gap"></div>
	</div>
	<div id="single">
		<div class="grid_12 alpha omega">
			<div class="breadcrumb">
				<p>Home</p>
			</div>
			<!--nreadcrumb-->
			<div id="content" class="full">
				<h1>The Seductive Community</h1>
				<p>
					Welcome to the Seductive Gaming Community. We like to pride ourselves on a mature and fun community, full of helpful people, playing a wide variety of games. Our servers are welcome to all, and we would love for you to join!
				</p>
				<p>
					Take a look around the site. Create an account and introduce yourself on the Forum. Become one with the community, and maybe, if you like us... you could donate? We'd love the support!
				</p>
			</div>
			<!--content-->
			<div class="clear"></div>
		</div>
		<!--grid_8 alpha -->
		<div class="clear"></div>
	</div>
	<div class="clear"></div>
</div><!--container_12-->
