<div id="page_bg" class="grid_12">
	<div class="grid_12 alpha omega">
		<div id="nav">
		    <ul class="sf-menu">
		      <li class="first"><a href="#">Home</a></li>
		      <li class="second"><a href="/forum/" target="_blank">Forum</a></li>
		    </ul>
		    <div class="clear"></div>
		</div><!--nav-->
	    </div><!--grid_12-->
	<div class="grid_12 alpha omega">
	    <div id="slider">
		<div class="item">
		    <div class="image"><a href="#"><img src="images/content/slider_pic.jpg" alt="slider image"></a></div>
		    <div class="details">
			<div class="cats">
				<span>&nbsp;//&nbsp;</span> Aaron Scherer
			    <span>&nbsp;//&nbsp;</span> August 27, 2012
			</div><!--cats-->
			<h2><a href="#">New Site!</a></h2>
			<div class="excerpt">
			    <p>Hey Guys! Working on the new site, so bear with me while i finish it!</p>
			</div><!--excerpt-->
		    </div><!--details-->
		    <div class="clear"></div>
		</div><!--item-->
	    </div><!--slider-->

	    <div id="slider_nav">

		<ul></ul>

	    </div><!--nav-->

	</div><!--grid_12-->
    <div class="grid_12 alpha omega">
	<div class="gap"></div>
    </div>
<div id="single">
                    
                        <div class="grid_12 alpha omega">
                            
                            <div class="breadcrumb">
                            
                                <p>Home &gt; <a href="#">World News</a> &gt; <a href="#">Full Width</a></p>
                                
                            </div><!--nreadcrumb-->
                            
                            <div id="content" class="full">
                            
                            	<h1>Fly Fishers Serving as Transports for Little Invaders</h1>
                                           
                                <p>Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Nulla vitae elit libero, a pharetra augue. <a href="#">Sed posuere consectetur est</a> at lobortis. Nullam id dolor id nibh ultricies vehicula ut id elit. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Sed posuere consectetur est at lobortis. Curabitur blandit tempus porttitor.</p>
                                
                                <blockquote><p>Vestibulum id ligula porta felis euismod semper. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Aenean lacinia bibendum nulla sed consectetur. Integer posuere erat a ant</p></blockquote>
                                
                                <p class="one_half">Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Nulla vitae elit libero, a pharetra augue. Sed posuere consectetur est at</p>
                                
                                <p class="one_half_last">Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Nulla vitae elit libero, a pharetra augue. Sed posuere consectetur est at </p>
                                
                                <p class="one_third">Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit</p>
                                
                                <p class="one_third">Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit</p>
                                
                                <p class="one_third_last">Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit</p>
                                
                            </div><!--content-->

                            <div class="clear"></div>

                        </div><!--grid_8 alpha -->

                        <div class="clear"></div>
                        
                    </div>
	<div class="clear"></div>
	</div><!--container_12-->
</div>
